### PR TITLE
Reauthentication with MQTT5 Enhanced Authentication (AUTH packet exchange) in autopaho

### LINKED ISSUE #212: Reauthentication with MQTT5 Enhanced Authentication (AUTH packet exchange) in autopaho
I noticed that autopaho does not support reauthentication MQTT5 enhanced authentication. This may be a feature that users need.

### PR DESCRIPTION
**Pull request by Widgle**
closes #212 

- [x] add Authenticate method to autopaho
- [x] add a test for autopaho Authenticate

### CODE REVIEW

**Comment by MattBrittan** [comment]
Would you like this added as-is or are you intending to add a test?

**Comment by Widgle** [comment]
@MattBrittan I'd like to try adding a test if it's OK.

**Comment by MattBrittan** [comment]
That's fine (just wanted to check you were not waiting on me (had not noticed that this was flagged as a draft).

**Comment by Widgle** [comment]
@MattBrittan Test was added. Thank you!

**Pull request merged**
