### PR TITLE
[TRIVIAL]: Add proxy support

### PR DESCRIPTION
**Pull request by Lorderot**
Trivial change to respect "all_proxy" env var, as it was done in paho.mqtt.golang library.
Taken from:
https://github.com/eclipse/paho.mqtt.golang/blob/master/netconn.go#L85

### CODE REVIEW

**Comment by Lorderot** [comment]
just an example of the change for https://github.com/eclipse/paho.golang/issues/143

**Comment by alsm** [comment]
Thanks for this, useful addition. Needs to pass the ECA before I can merge it.

**Comment by Lorderot** [comment]
@alsm thanks, I've signed the ECA.

**Comment by Lorderot** [comment]
hi @alsm, can we proceed with this? thanks!

**Pull request merged**
