### PR TITLE
Fix StandardRouter topic matching for shared subscriptions

### LINKED ISSUE #93: Shared subscriptions not working with StandardRouter due to wrong handler matching.
**Describe the bug**
Shared subscriptions do not correctly work with the `StandardRouter`. Topic-Route Matching is incorrect.

**To reproduce**
Subscribe to: `$share/group1/my/topic`
Publish to: `my/topic`

**Debug output**
The message was received but not passed to the corresponding handler due to incorrect matching algorithm.

**Expected behaviour**
Topic matching handler is called.

**Software used:**
- Client version v0.10.0

**Problem**
The matching of the incoming topic to a registered handler is incorrect. Code below show that only the `$share` sgement is removed, but the `group` segment must be removed too!

Code: paho/router.go line 141
```
if strings.HasPrefix(route, "$share") {
    result = strings.Split(route, "/")[1:] // <-- only removes `$share`. Group must be removed too!
```

### PR DESCRIPTION
**Pull request by lukaskirner**
**ECA - Eclipse Contributer Agreement**

Ensure you have a valid, signed [ECA](https://www.eclipse.org/legal/ECA.php) for the email address associated with your Github account (or you sign off your PR with an ECA'd address)

Please provide enough information so that others can review your pull request: See issue #93 

**Closing issues**
Put `closes #93` in your comment to auto-close the issue that your PR fixes.

### CODE REVIEW

**Comment by alsm** [comment]
Thanks for noticing and fixing this

**Comment by gabrielruiu** [comment]
Can you please make a new tag release that contains this fix?

**Comment by florianmaier101178** [comment]
Are there any plans for a tag release containing this fix. This  would be really helpful for us.

**Comment by lukaskirner** [comment]
@florianmaier101178 Just copy the new and fixed StandardRouter implementation into your project and use it.

**Pull request merged**
